---
openapi: 3.0.1
info:
  title: Musicnet
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  "/api/v1/playlists":
    get:
      summary: retrieves playlists
      tags:
      - Playlist
      security:
      - bearerAuth: []
      responses:
        '200':
          description: playlists found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  "/api/v1/playlists/{id}":
    get:
      summary: Retrieves a playlist
      tags:
      - Playlist
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: playlist found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  public:
                    type: boolean
                required:
                - id
                - name
                - public
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 0.0.0.0:3001
