# api-docs/v1/swagger.yaml
openapi: 3.0.3
info:
  title: MusicNet API
paths:
  /api/v1/playlists/{playlistId}:
    get:
      summary: Get a playlist by ID
      parameters:
        - name: playlistId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaylistResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/RecordNotFound'

components:
  schemas:
    PlaylistResponse:
      type: object
      properties:
        id:
          type: integer
        spotify_id:
          type: string
        snapshot_id:
          type: string
        name:
          type: string
        url:
          type: string
        public:
          type: boolean

  responses:
    UnauthorizedError:
      description: Unauthorized Error
      content:
        application/json:
          example:
            error: Unauthorized
            message: Invalid or missing authorization token

    RecordNotFound:
      description: Record Not Found
      content:
        application/json:
          example:
            error: Not Found
            message: The requested resource was not found
